# hugo.toml
baseURL = "https://thesfb.github.io/"
languageCode = "en-us"
title = ""
theme = "PaperMod"


enableRobotsTXT = true
[pagination]
  pagerSize = 10


[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowRecentPosts = true
  mainSections = ["posts"]

  

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Resume"
  url = "/about/"
  weight = 2

[params.profileMode]
  enabled = true
  title = "Report By Sudhanshu"
  subtitle = "Rust - Web3 - Zero Knowledge - Projects"
  imageUrl = ""
  imageTitle = ""
  imageWidth = 120
  imageHeight = 120

  [[params.profileMode.buttons]]
    name = "Posts"
    url = "/posts/"

  [[params.profileMode.buttons]]
    name = "Resume"
    url = "/about/"
    
  
