# hugo.toml
baseURL = "https://thesfb.github.io/"
languageCode = "en-us"
title = "Another Day"
theme = "PaperMod"


enableRobotsTXT = true
[pagination]
  pagerSize = 10


[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
